# Generated by Django 5.2.5 on 2025-08-21 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('bounced', 'Bounced'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('last_step', models.IntegerField(blank=True, null=True)),
                ('partial_payload', models.JSONField(default=dict)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='survey_sessions.surveyinvitation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='surveys.survey')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('survey', 'invitation'), name='uq_session_survey_invitation')],
            },
        ),
    ]
